name: dermatrack
description: A mobile companion for longitudinal acne severity monitoring and self-care tracking.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  path_provider: ^2.1.4
  shared_preferences: ^2.3.2
  supabase_flutter: ^2.5.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
